### ISSUE TITLE
Mixing up company and regimen some on this page

### ISSUE THREAD

**Issue by rgaston5** [chrisalbon/notes_on_data_science_machine_learning_and_artificial_intelligence#101]
There are a few places on this page where my novice eye thinks you might be mixing up company and regimen, like:
# Create a groupby variable that groups preTestScores by regiment
groupby_regiment = df['preTestScore'].groupby(df['company'])
groupby_regiment

**Comment by chrisalbon** [comment]
fixed thanks!
