### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by mroswell** [chrisalbon/notes_on_data_science_machine_learning_and_artificial_intelligence#103]
typos on https://chrisalbon.com/python/geocoding_and_reverse_geocoding.html :

phyiscal --> physical (twice)
it's --> its (twice - "It's" with an apostrophe means 'it is')
seperate --> separate (twice)
seperated --> separated
unneccesary -->. unnecessary
avaliable --> available

(Let me know if you want more of these kinds of corrections on other pages.)

**Comment by chrisalbon** [comment]
Finally getting to these! Thanks so much!
