### ISSUE TITLE
Compare Two Dictionaries -Python

### ISSUE THREAD

**Issue by godfatherX** [chrisalbon/notes_on_data_science_machine_learning_and_artificial_intelligence#104]
I got this error while working on Jupyter notebook. Please let me know if there is something wrong.

I am following your notes as it is quite helpful.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-46-fbd5c57283fe> in <module>()
      1 # Find countries where the amount of exports matches the amount of imports
----> 2 importers.items() & exporters.items()

TypeError: unsupported operand type(s) for &: 'list' and 'list'

**Comment by chrisalbon** [comment]
Are you using Python 3?
