### ISSUE TITLE
copy/paste scar in accuracy definition denominator

### ISSUE THREAD

**Issue by replacedwings** [chrisalbon/notes_on_data_science_machine_learning_and_artificial_intelligence#110]
accuracy denominator double counts TP...one 'TP' should be 'FP'.

![screen shot 2017-07-24 at 3 11 31 pm](https://user-images.githubusercontent.com/4825493/28544988-6e7c8fc2-7082-11e7-8d1f-59be7cea6de2.png)

**Comment by chrisalbon** [comment]
fixed thanks!

**Comment by replacedwings** [comment]
Thank you!
