### ISSUE TITLE
Details of the "Confusion Matrix"

### ISSUE THREAD

**Issue by elephantpanini** [chrisalbon/notes_on_data_science_machine_learning_and_artificial_intelligence#111]
The printed example says:
- "all 20 setosa plants," but the confusion matrix only indicates 11.
- "17 of the versicolor plants correctly, but mis-predicted two of the versicolor plants as virginica," but the confusion matrix indicates 16 correct versicolor and only 1 mispredicted virginica.

Thanks in advance for checking this! Want to make sure I'm reading the results correctly.

**Comment by chrisalbon** [comment]
fixed thx!
