### ISSUE TITLE
Issues with the naive bayes article

### ISSUE THREAD

**Issue by modqhx** [chrisalbon/notes_on_data_science_machine_learning_and_artificial_intelligence#60]
It seems the conclusion for the [article](https://chrisalbon.com/machine-learning/naive_bayes_classifier_from_scratch.html) is not right! 
You mention `Because the numerator of the posterior for male is greater than female, then we predict that the person is male.`, but the posterior for female is higher here. Might have missed the `e-09` :) 
Another issue was the likelihood in the beginning: you mention its `p(class)  is called the likelihood`, rather it should be `p(data|class)` as likelihood(our observed data)

**Comment by chrisalbon** [comment]
Good catch! _shakes fist at e-09_ :)

Ficed
