### ISSUE TITLE
Formula for accuracy is wrong.

### ISSUE THREAD

**Issue by sharanry** [chrisalbon/notes_on_data_science_machine_learning_and_artificial_intelligence#89]
[https://chrisalbon.com/machine-learning/precision_recall_and_F1_scores.html](url)
Given :
(TP+FN)/(TP+FP+FN+TN)

Correct:
(TP+TN)/(TP+FP+FN+TN)

Source:
[https://www.cs.cornell.edu/courses/cs578/2003fa/performance_measures.pdf](url)

**Comment by chrisalbon** [comment]
fixed!
