### ISSUE TITLE
Issues: The Probability An Economy Seat Is An Aisle? 

### ISSUE THREAD

**Issue by skyper91** [chrisalbon/notes_on_data_science_machine_learning_and_artificial_intelligence#91]
Hey Chris, just found your blog through the Harvard CS109 course, nice stuff. 

Noticed some oddities in this article I don't quite understand... could you explain them to me? 

### 1. How can seat D in the six seater be non-aisle?
> An aircraft with six seats per row
> rows6 = [0,1,1,0,1,0, np.nan, np.nan, np.nan]

Either there is no aisle between D&E (E should be 0) or there is (D should be 1). 

### 2. 747-400 has 10 seaters in configs 3-4-3 
> No flight has more than nine rows.

### 3. 8 seater configs
> rows8 = [0,0,1,1,1,1,0,0, np.nan]

There's also the pretty common 2-4-2 layout, I think you should use (or add!) that permutation. Never actually seen a 3-2-3 layout as you describe

**Comment by chrisalbon** [comment]
fixed!
