### ISSUE TITLE
Bessel's Correction - Correction

### ISSUE THREAD

**Issue by KSafran** [chrisalbon/notes_on_data_science_machine_learning_and_artificial_intelligence#94]
Huge fan of the pod and your website!

I've seen that explanation for the need for Bessel's correction in a few places, but it's not quite correct. The bias in a naive standard deviation estimate comes from the fact that you're measuring the squared deviance of your sample observations from the _sample mean_, which will be smaller by construction than the squared deviance of your sample observations from the true population mean. Wikipedia's explanation [here](https://en.wikipedia.org/wiki/Bessel%27s_correction#Source_of_bias) might be more clear.

**Comment by chrisalbon** [comment]
fixed!
