### ISSUE TITLE
DataFrame column mixup

### ISSUE THREAD

**Issue by Jessime** [chrisalbon/notes_on_data_science_machine_learning_and_artificial_intelligence#95]
Hello!

I think in your [Apply Operations To Groups In Pandas](https://chrisalbon.com/python/pandas_apply_operations_to_groups.html) page, you mix up "company" and "regiment" columns. For example, in cell 3, you write:

```python
# Create a groupby variable that groups preTestScores by regiment
groupby_regiment = df['preTestScore'].groupby(df['company'])
groupby_regiment
```

This mistake seems to be propagated through the next few cells.

**Comment by chrisalbon** [comment]
fixed!
