### ISSUE TITLE
Small tweak to avoid copy & paste issues

### ISSUE THREAD

**Issue by tlockney** [chrisalbon/notes_on_data_science_machine_learning_and_artificial_intelligence#99]
In your bash example for opening Jupyter with a non-default browser, you might want to switch to this form:

```bash
env BROWSER=/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome jupyter notebook
```
The important bit is the `env` at the beginning. Since your example is explicitly running this in a bash script, it's not terribly important, but for anyone who tries to cut and paste that line into their shell, it may fail depending on which shell they're using (e.g., Fish shell and possibly csh derivatives).

**Comment by chrisalbon** [comment]
fixed thanks!
